### ISSUE TITLE
Create logo for social network

### ISSUE THREAD

**Issue by zastava8** [zastava8/PHP-Social-Media-Site#2]
Need to create logo for the social network that matches its name "WeConnect"

**Comment by blgold** [comment]
From what John showed me in class today it look done and all he had to do was incorporated into the program

**Comment by Zombie31** [comment]
![world](https://cloud.githubusercontent.com/assets/13005036/14654819/1993f430-0645-11e6-8680-5dfe5f8c0138.jpg)

**Comment by Zombie31** [comment]
Logo done

**Comment by Zombie31** [comment]
Working on getting it plugged into the header
